
import java.util.Timer;
import java.util.TimerTask;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class tugas2 extends javax.swing.JFrame {
    int time = 25; //isi
    /**
     * Creates new form tugas2
     */
    public tugas2() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eWaktu = new javax.swing.JLabel();
        eMulai = new javax.swing.JButton();
        eKeluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        eWaktu.setFont(new java.awt.Font("Segoe UI", 1, 85)); // NOI18N
        eWaktu.setText("25");
        jPanel1.add(eWaktu);

        eMulai.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        eMulai.setText("MULAI");
        eMulai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eMulaiMouseClicked(evt);
            }
        });
        eMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMulaiActionPerformed(evt);
            }
        });
        jPanel1.add(eMulai);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 80, 120, 170);

        eKeluar.setBackground(new java.awt.Color(242, 215, 185));
        eKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eKeluar.setForeground(new java.awt.Color(242, 215, 185));
        eKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit (2).png"))); // NOI18N
        eKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(eKeluar);
        eKeluar.setBounds(490, 310, 60, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Waktu Terus Berjalan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 200, 130, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tok..");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 170, 37, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tok..");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 140, 37, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tok..");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 110, 37, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngegg (32) (1).png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 70, 160, 200);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("TIME IS MONEY");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 10, 190, 40);

        jPanel2.setBackground(new java.awt.Color(242, 215, 185));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 560, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clock.jpg"))); // NOI18N
        background.setText("jLabel2");
        getContentPane().add(background);
        background.setBounds(0, 0, 560, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMulaiActionPerformed
        Timer timer = new Timer(); //nama variabel baru
        time = 25;
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                if (time >= 0) {
                    eWaktu.setText(Integer.toString(time--));
                } else {
                    timer.cancel();
            }
            }            
        };
        timer.scheduleAtFixedRate(task, 500, 500);
    }//GEN-LAST:event_eMulaiActionPerformed

    private void eMulaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eMulaiMouseClicked
      
    }//GEN-LAST:event_eMulaiMouseClicked

    private void eKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_eKeluarActionPerformed
    private int coundownValue = 25;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton eKeluar;
    private javax.swing.JButton eMulai;
    private javax.swing.JLabel eWaktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
